### ISSUE TITLE
i want to use orientdb with php but get connecting error

### ISSUE THREAD

**Issue by AhsanAbrar** [orientechnologies/PhpOrient#20]
Fatal error: Uncaught PhpOrient\Exceptions\SocketException: socket_read(): unable to read from socket [104]: Connection reset by peer in D:\laragon\www\PhpOrient\src\PhpOrient\Protocols\Binary\OrientSocket.php:147 Stack trace: #0 D:\laragon\www\PhpOrient\src\PhpOrient\Protocols\Binary\OrientSocket.php(94): PhpOrient\Protocols\Binary\OrientSocket->read(2) #1 D:\laragon\www\PhpOrient\src\PhpOrient\Protocols\Binary\SocketTransport.php(146): PhpOrient\Protocols\Binary\OrientSocket->connect() #2 D:\laragon\www\PhpOrient\src\PhpOrient\Protocols\Binary\Abstracts\Operation.php(76): PhpOrient\Protocols\Binary\SocketTransport->getSocket() #3 D:\laragon\www\PhpOrient\src\PhpOrient\Protocols\Binary\SocketTransport.php(223): PhpOrient\Protocols\Binary\Abstracts\Operation->__construct(Object(PhpOrient\Protocols\Binary\SocketTransport)) #4 D:\laragon\www\PhpOrient\src\PhpOrient\Protocols\Binary\SocketTransport.php(161): PhpOrient\Protocols\Binary\SocketTransport->operationFactory('PhpOrient\Proto...', Array) #5 D:\laragon\www\PhpOrient in D:\laragon\www\PhpOrient\src\PhpOrient\Protocols\Binary\OrientSocket.php on line 147

what mean of this error?

**Comment by max-kuk** [comment]
Hi @AhsanAbrar , you should use 2424 port in your client settings. See [link](https://stackoverflow.com/questions/39564035/orientdb-unable-to-read-from-socket)
